=begin
#UltraCart Rest API V2

#This is the next generation UltraCart REST API...

OpenAPI spec version: 2.0.0
Contact: support@ultracart.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module UltraCartAdminV2

  class OrderInternal
    # True if the order has been exported to QuickBooks. If QuickBooks is not configured, then this will already be true
    attr_accessor :exported_to_accounting

    # Merchant notes
    attr_accessor :merchant_notes

    # If placed via the BEOE, this is the user that placed the order
    attr_accessor :placed_by_user

    # User that issued the refund
    attr_accessor :refund_by_user

    # Sales rep code associated with the order
    attr_accessor :sales_rep_code


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'exported_to_accounting' => :'exported_to_accounting',
        :'merchant_notes' => :'merchant_notes',
        :'placed_by_user' => :'placed_by_user',
        :'refund_by_user' => :'refund_by_user',
        :'sales_rep_code' => :'sales_rep_code'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'exported_to_accounting' => :'BOOLEAN',
        :'merchant_notes' => :'String',
        :'placed_by_user' => :'String',
        :'refund_by_user' => :'String',
        :'sales_rep_code' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'exported_to_accounting')
        self.exported_to_accounting = attributes[:'exported_to_accounting']
      end

      if attributes.has_key?(:'merchant_notes')
        self.merchant_notes = attributes[:'merchant_notes']
      end

      if attributes.has_key?(:'placed_by_user')
        self.placed_by_user = attributes[:'placed_by_user']
      end

      if attributes.has_key?(:'refund_by_user')
        self.refund_by_user = attributes[:'refund_by_user']
      end

      if attributes.has_key?(:'sales_rep_code')
        self.sales_rep_code = attributes[:'sales_rep_code']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new

      if !@sales_rep_code.nil? && @sales_rep_code.to_s.length > 10
        invalid_properties.push("invalid value for 'sales_rep_code', the character length must be smaller than or equal to 10.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@sales_rep_code.nil? && @sales_rep_code.to_s.length > 10
      return true
    end

    # Custom attribute writer method with validation
    # @param [Object] sales_rep_code Value to be assigned
    def sales_rep_code=(sales_rep_code)

      if !sales_rep_code.nil? && sales_rep_code.to_s.length > 10
        fail ArgumentError, "invalid value for 'sales_rep_code', the character length must be smaller than or equal to 10."
      end

      @sales_rep_code = sales_rep_code
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          exported_to_accounting == o.exported_to_accounting &&
          merchant_notes == o.merchant_notes &&
          placed_by_user == o.placed_by_user &&
          refund_by_user == o.refund_by_user &&
          sales_rep_code == o.sales_rep_code
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [exported_to_accounting, merchant_notes, placed_by_user, refund_by_user, sales_rep_code].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = UltraCartAdminV2.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
