=begin
#UltraCart Rest API V2

#UltraCart REST API Version 2

The version of the OpenAPI document: 2.0.0
Contact: support@ultracart.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1-SNAPSHOT

=end

require 'date'
require 'time'

module UltracartClient
  class ConversationPbxAddress
    # Twilio Address SID
    attr_accessor :address_sid

    # City
    attr_accessor :city

    # Conversation Pbx Address UUID
    attr_accessor :conversation_pbx_address_uuid

    # ISO country code (2 characters)
    attr_accessor :country_code

    # Customer name
    attr_accessor :customer_name

    # Friendly name for the address
    attr_accessor :friendly_name

    # Merchant Id
    attr_accessor :merchant_id

    # Postal code
    attr_accessor :postal_code

    # State/Province/Region
    attr_accessor :region

    # Street address
    attr_accessor :street

    # Whether the address is valid (validated or verified)
    attr_accessor :valid

    # Whether the address has been validated by Twilio
    attr_accessor :validated

    # Whether the address has been verified by Twilio
    attr_accessor :verified

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'address_sid' => :'address_sid',
        :'city' => :'city',
        :'conversation_pbx_address_uuid' => :'conversation_pbx_address_uuid',
        :'country_code' => :'country_code',
        :'customer_name' => :'customer_name',
        :'friendly_name' => :'friendly_name',
        :'merchant_id' => :'merchant_id',
        :'postal_code' => :'postal_code',
        :'region' => :'region',
        :'street' => :'street',
        :'valid' => :'valid',
        :'validated' => :'validated',
        :'verified' => :'verified'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'address_sid' => :'String',
        :'city' => :'String',
        :'conversation_pbx_address_uuid' => :'String',
        :'country_code' => :'String',
        :'customer_name' => :'String',
        :'friendly_name' => :'String',
        :'merchant_id' => :'String',
        :'postal_code' => :'String',
        :'region' => :'String',
        :'street' => :'String',
        :'valid' => :'Boolean',
        :'validated' => :'Boolean',
        :'verified' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `UltracartClient::ConversationPbxAddress` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `UltracartClient::ConversationPbxAddress`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'address_sid')
        self.address_sid = attributes[:'address_sid']
      end

      if attributes.key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.key?(:'conversation_pbx_address_uuid')
        self.conversation_pbx_address_uuid = attributes[:'conversation_pbx_address_uuid']
      end

      if attributes.key?(:'country_code')
        self.country_code = attributes[:'country_code']
      end

      if attributes.key?(:'customer_name')
        self.customer_name = attributes[:'customer_name']
      end

      if attributes.key?(:'friendly_name')
        self.friendly_name = attributes[:'friendly_name']
      end

      if attributes.key?(:'merchant_id')
        self.merchant_id = attributes[:'merchant_id']
      end

      if attributes.key?(:'postal_code')
        self.postal_code = attributes[:'postal_code']
      end

      if attributes.key?(:'region')
        self.region = attributes[:'region']
      end

      if attributes.key?(:'street')
        self.street = attributes[:'street']
      end

      if attributes.key?(:'valid')
        self.valid = attributes[:'valid']
      end

      if attributes.key?(:'validated')
        self.validated = attributes[:'validated']
      end

      if attributes.key?(:'verified')
        self.verified = attributes[:'verified']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@address_sid.nil? && @address_sid.to_s.length > 50
        invalid_properties.push('invalid value for "address_sid", the character length must be smaller than or equal to 50.')
      end

      if !@city.nil? && @city.to_s.length > 100
        invalid_properties.push('invalid value for "city", the character length must be smaller than or equal to 100.')
      end

      if !@conversation_pbx_address_uuid.nil? && @conversation_pbx_address_uuid.to_s.length > 50
        invalid_properties.push('invalid value for "conversation_pbx_address_uuid", the character length must be smaller than or equal to 50.')
      end

      if !@country_code.nil? && @country_code.to_s.length > 2
        invalid_properties.push('invalid value for "country_code", the character length must be smaller than or equal to 2.')
      end

      if !@customer_name.nil? && @customer_name.to_s.length > 100
        invalid_properties.push('invalid value for "customer_name", the character length must be smaller than or equal to 100.')
      end

      if !@friendly_name.nil? && @friendly_name.to_s.length > 100
        invalid_properties.push('invalid value for "friendly_name", the character length must be smaller than or equal to 100.')
      end

      if !@merchant_id.nil? && @merchant_id.to_s.length > 5
        invalid_properties.push('invalid value for "merchant_id", the character length must be smaller than or equal to 5.')
      end

      if !@postal_code.nil? && @postal_code.to_s.length > 20
        invalid_properties.push('invalid value for "postal_code", the character length must be smaller than or equal to 20.')
      end

      if !@region.nil? && @region.to_s.length > 50
        invalid_properties.push('invalid value for "region", the character length must be smaller than or equal to 50.')
      end

      if !@street.nil? && @street.to_s.length > 200
        invalid_properties.push('invalid value for "street", the character length must be smaller than or equal to 200.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@address_sid.nil? && @address_sid.to_s.length > 50
      return false if !@city.nil? && @city.to_s.length > 100
      return false if !@conversation_pbx_address_uuid.nil? && @conversation_pbx_address_uuid.to_s.length > 50
      return false if !@country_code.nil? && @country_code.to_s.length > 2
      return false if !@customer_name.nil? && @customer_name.to_s.length > 100
      return false if !@friendly_name.nil? && @friendly_name.to_s.length > 100
      return false if !@merchant_id.nil? && @merchant_id.to_s.length > 5
      return false if !@postal_code.nil? && @postal_code.to_s.length > 20
      return false if !@region.nil? && @region.to_s.length > 50
      return false if !@street.nil? && @street.to_s.length > 200
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] address_sid Value to be assigned
    def address_sid=(address_sid)
      if !address_sid.nil? && address_sid.to_s.length > 50
        fail ArgumentError, 'invalid value for "address_sid", the character length must be smaller than or equal to 50.'
      end

      @address_sid = address_sid
    end

    # Custom attribute writer method with validation
    # @param [Object] city Value to be assigned
    def city=(city)
      if !city.nil? && city.to_s.length > 100
        fail ArgumentError, 'invalid value for "city", the character length must be smaller than or equal to 100.'
      end

      @city = city
    end

    # Custom attribute writer method with validation
    # @param [Object] conversation_pbx_address_uuid Value to be assigned
    def conversation_pbx_address_uuid=(conversation_pbx_address_uuid)
      if !conversation_pbx_address_uuid.nil? && conversation_pbx_address_uuid.to_s.length > 50
        fail ArgumentError, 'invalid value for "conversation_pbx_address_uuid", the character length must be smaller than or equal to 50.'
      end

      @conversation_pbx_address_uuid = conversation_pbx_address_uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] country_code Value to be assigned
    def country_code=(country_code)
      if !country_code.nil? && country_code.to_s.length > 2
        fail ArgumentError, 'invalid value for "country_code", the character length must be smaller than or equal to 2.'
      end

      @country_code = country_code
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_name Value to be assigned
    def customer_name=(customer_name)
      if !customer_name.nil? && customer_name.to_s.length > 100
        fail ArgumentError, 'invalid value for "customer_name", the character length must be smaller than or equal to 100.'
      end

      @customer_name = customer_name
    end

    # Custom attribute writer method with validation
    # @param [Object] friendly_name Value to be assigned
    def friendly_name=(friendly_name)
      if !friendly_name.nil? && friendly_name.to_s.length > 100
        fail ArgumentError, 'invalid value for "friendly_name", the character length must be smaller than or equal to 100.'
      end

      @friendly_name = friendly_name
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_id Value to be assigned
    def merchant_id=(merchant_id)
      if !merchant_id.nil? && merchant_id.to_s.length > 5
        fail ArgumentError, 'invalid value for "merchant_id", the character length must be smaller than or equal to 5.'
      end

      @merchant_id = merchant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] postal_code Value to be assigned
    def postal_code=(postal_code)
      if !postal_code.nil? && postal_code.to_s.length > 20
        fail ArgumentError, 'invalid value for "postal_code", the character length must be smaller than or equal to 20.'
      end

      @postal_code = postal_code
    end

    # Custom attribute writer method with validation
    # @param [Object] region Value to be assigned
    def region=(region)
      if !region.nil? && region.to_s.length > 50
        fail ArgumentError, 'invalid value for "region", the character length must be smaller than or equal to 50.'
      end

      @region = region
    end

    # Custom attribute writer method with validation
    # @param [Object] street Value to be assigned
    def street=(street)
      if !street.nil? && street.to_s.length > 200
        fail ArgumentError, 'invalid value for "street", the character length must be smaller than or equal to 200.'
      end

      @street = street
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          address_sid == o.address_sid &&
          city == o.city &&
          conversation_pbx_address_uuid == o.conversation_pbx_address_uuid &&
          country_code == o.country_code &&
          customer_name == o.customer_name &&
          friendly_name == o.friendly_name &&
          merchant_id == o.merchant_id &&
          postal_code == o.postal_code &&
          region == o.region &&
          street == o.street &&
          valid == o.valid &&
          validated == o.validated &&
          verified == o.verified
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [address_sid, city, conversation_pbx_address_uuid, country_code, customer_name, friendly_name, merchant_id, postal_code, region, street, valid, validated, verified].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = UltracartClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
