=begin
#UltraCart Rest API V2

#UltraCart REST API Version 2

The version of the OpenAPI document: 2.0.0
Contact: support@ultracart.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1-SNAPSHOT

=end

require 'date'
require 'time'

module UltracartClient
  class ConversationPbxPayConnector
    # Description of the connector
    attr_accessor :description

    # Environment the connector points at.  Only live connectors are returned.  Sandbox and unconfigured connectors are ignored.
    attr_accessor :environment

    # Friendly name of the connector as shown in the Twilio console
    attr_accessor :friendly_name

    # Merchant Id
    attr_accessor :merchant_id

    # Payment processor behind this connector
    attr_accessor :processor

    # The processor account this connector is bound to (Stripe connected account id or Braintree merchant id).  A payment captured with this connector can only be charged within this account.
    attr_accessor :processor_account_id

    # Twilio installed add-on SID for this connector
    attr_accessor :sid

    # Unique name of the connector.  This is the value used for the paymentConnector attribute of the Twilio Pay verb.
    attr_accessor :unique_name

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'description' => :'description',
        :'environment' => :'environment',
        :'friendly_name' => :'friendly_name',
        :'merchant_id' => :'merchant_id',
        :'processor' => :'processor',
        :'processor_account_id' => :'processor_account_id',
        :'sid' => :'sid',
        :'unique_name' => :'unique_name'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'description' => :'String',
        :'environment' => :'String',
        :'friendly_name' => :'String',
        :'merchant_id' => :'String',
        :'processor' => :'String',
        :'processor_account_id' => :'String',
        :'sid' => :'String',
        :'unique_name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `UltracartClient::ConversationPbxPayConnector` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `UltracartClient::ConversationPbxPayConnector`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'environment')
        self.environment = attributes[:'environment']
      end

      if attributes.key?(:'friendly_name')
        self.friendly_name = attributes[:'friendly_name']
      end

      if attributes.key?(:'merchant_id')
        self.merchant_id = attributes[:'merchant_id']
      end

      if attributes.key?(:'processor')
        self.processor = attributes[:'processor']
      end

      if attributes.key?(:'processor_account_id')
        self.processor_account_id = attributes[:'processor_account_id']
      end

      if attributes.key?(:'sid')
        self.sid = attributes[:'sid']
      end

      if attributes.key?(:'unique_name')
        self.unique_name = attributes[:'unique_name']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@description.nil? && @description.to_s.length > 250
        invalid_properties.push('invalid value for "description", the character length must be smaller than or equal to 250.')
      end

      if !@friendly_name.nil? && @friendly_name.to_s.length > 100
        invalid_properties.push('invalid value for "friendly_name", the character length must be smaller than or equal to 100.')
      end

      if !@merchant_id.nil? && @merchant_id.to_s.length > 5
        invalid_properties.push('invalid value for "merchant_id", the character length must be smaller than or equal to 5.')
      end

      if !@processor_account_id.nil? && @processor_account_id.to_s.length > 100
        invalid_properties.push('invalid value for "processor_account_id", the character length must be smaller than or equal to 100.')
      end

      if !@sid.nil? && @sid.to_s.length > 50
        invalid_properties.push('invalid value for "sid", the character length must be smaller than or equal to 50.')
      end

      if !@unique_name.nil? && @unique_name.to_s.length > 100
        invalid_properties.push('invalid value for "unique_name", the character length must be smaller than or equal to 100.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@description.nil? && @description.to_s.length > 250
      environment_validator = EnumAttributeValidator.new('String', ["live"])
      return false unless environment_validator.valid?(@environment)
      return false if !@friendly_name.nil? && @friendly_name.to_s.length > 100
      return false if !@merchant_id.nil? && @merchant_id.to_s.length > 5
      processor_validator = EnumAttributeValidator.new('String', ["stripe", "braintree", "generic", "unknown"])
      return false unless processor_validator.valid?(@processor)
      return false if !@processor_account_id.nil? && @processor_account_id.to_s.length > 100
      return false if !@sid.nil? && @sid.to_s.length > 50
      return false if !@unique_name.nil? && @unique_name.to_s.length > 100
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if !description.nil? && description.to_s.length > 250
        fail ArgumentError, 'invalid value for "description", the character length must be smaller than or equal to 250.'
      end

      @description = description
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] environment Object to be assigned
    def environment=(environment)
      validator = EnumAttributeValidator.new('String', ["live"])
      unless validator.valid?(environment)
        fail ArgumentError, "invalid value for \"environment\", must be one of #{validator.allowable_values}."
      end
      @environment = environment
    end

    # Custom attribute writer method with validation
    # @param [Object] friendly_name Value to be assigned
    def friendly_name=(friendly_name)
      if !friendly_name.nil? && friendly_name.to_s.length > 100
        fail ArgumentError, 'invalid value for "friendly_name", the character length must be smaller than or equal to 100.'
      end

      @friendly_name = friendly_name
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_id Value to be assigned
    def merchant_id=(merchant_id)
      if !merchant_id.nil? && merchant_id.to_s.length > 5
        fail ArgumentError, 'invalid value for "merchant_id", the character length must be smaller than or equal to 5.'
      end

      @merchant_id = merchant_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] processor Object to be assigned
    def processor=(processor)
      validator = EnumAttributeValidator.new('String', ["stripe", "braintree", "generic", "unknown"])
      unless validator.valid?(processor)
        fail ArgumentError, "invalid value for \"processor\", must be one of #{validator.allowable_values}."
      end
      @processor = processor
    end

    # Custom attribute writer method with validation
    # @param [Object] processor_account_id Value to be assigned
    def processor_account_id=(processor_account_id)
      if !processor_account_id.nil? && processor_account_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "processor_account_id", the character length must be smaller than or equal to 100.'
      end

      @processor_account_id = processor_account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] sid Value to be assigned
    def sid=(sid)
      if !sid.nil? && sid.to_s.length > 50
        fail ArgumentError, 'invalid value for "sid", the character length must be smaller than or equal to 50.'
      end

      @sid = sid
    end

    # Custom attribute writer method with validation
    # @param [Object] unique_name Value to be assigned
    def unique_name=(unique_name)
      if !unique_name.nil? && unique_name.to_s.length > 100
        fail ArgumentError, 'invalid value for "unique_name", the character length must be smaller than or equal to 100.'
      end

      @unique_name = unique_name
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          description == o.description &&
          environment == o.environment &&
          friendly_name == o.friendly_name &&
          merchant_id == o.merchant_id &&
          processor == o.processor &&
          processor_account_id == o.processor_account_id &&
          sid == o.sid &&
          unique_name == o.unique_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [description, environment, friendly_name, merchant_id, processor, processor_account_id, sid, unique_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = UltracartClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
