=begin
#UltraCart Rest API V2

#UltraCart REST API Version 2

The version of the OpenAPI document: 2.0.0
Contact: support@ultracart.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1-SNAPSHOT

=end

require 'date'
require 'time'

module UltracartClient
  class EmailSettings
    attr_accessor :marketing_esp_domain_user

    attr_accessor :marketing_esp_domain_uuid

    attr_accessor :marketing_esp_friendly_name

    attr_accessor :postcard_from_address1

    attr_accessor :postcard_from_address2

    attr_accessor :postcard_from_city

    attr_accessor :postcard_from_name

    attr_accessor :postcard_from_postal_code

    attr_accessor :postcard_from_state

    # True if the Reviews.io integration is configured
    attr_accessor :reviews_io_configured

    attr_accessor :sms_esp_twilio_uuid

    attr_accessor :sms_phone_number

    attr_accessor :transactional_esp_domain_user

    attr_accessor :transactional_esp_domain_uuid

    attr_accessor :transactional_esp_friendly_name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'marketing_esp_domain_user' => :'marketing_esp_domain_user',
        :'marketing_esp_domain_uuid' => :'marketing_esp_domain_uuid',
        :'marketing_esp_friendly_name' => :'marketing_esp_friendly_name',
        :'postcard_from_address1' => :'postcard_from_address1',
        :'postcard_from_address2' => :'postcard_from_address2',
        :'postcard_from_city' => :'postcard_from_city',
        :'postcard_from_name' => :'postcard_from_name',
        :'postcard_from_postal_code' => :'postcard_from_postal_code',
        :'postcard_from_state' => :'postcard_from_state',
        :'reviews_io_configured' => :'reviews_io_configured',
        :'sms_esp_twilio_uuid' => :'sms_esp_twilio_uuid',
        :'sms_phone_number' => :'sms_phone_number',
        :'transactional_esp_domain_user' => :'transactional_esp_domain_user',
        :'transactional_esp_domain_uuid' => :'transactional_esp_domain_uuid',
        :'transactional_esp_friendly_name' => :'transactional_esp_friendly_name'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'marketing_esp_domain_user' => :'String',
        :'marketing_esp_domain_uuid' => :'String',
        :'marketing_esp_friendly_name' => :'String',
        :'postcard_from_address1' => :'String',
        :'postcard_from_address2' => :'String',
        :'postcard_from_city' => :'String',
        :'postcard_from_name' => :'String',
        :'postcard_from_postal_code' => :'String',
        :'postcard_from_state' => :'String',
        :'reviews_io_configured' => :'Boolean',
        :'sms_esp_twilio_uuid' => :'String',
        :'sms_phone_number' => :'String',
        :'transactional_esp_domain_user' => :'String',
        :'transactional_esp_domain_uuid' => :'String',
        :'transactional_esp_friendly_name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `UltracartClient::EmailSettings` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `UltracartClient::EmailSettings`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'marketing_esp_domain_user')
        self.marketing_esp_domain_user = attributes[:'marketing_esp_domain_user']
      end

      if attributes.key?(:'marketing_esp_domain_uuid')
        self.marketing_esp_domain_uuid = attributes[:'marketing_esp_domain_uuid']
      end

      if attributes.key?(:'marketing_esp_friendly_name')
        self.marketing_esp_friendly_name = attributes[:'marketing_esp_friendly_name']
      end

      if attributes.key?(:'postcard_from_address1')
        self.postcard_from_address1 = attributes[:'postcard_from_address1']
      end

      if attributes.key?(:'postcard_from_address2')
        self.postcard_from_address2 = attributes[:'postcard_from_address2']
      end

      if attributes.key?(:'postcard_from_city')
        self.postcard_from_city = attributes[:'postcard_from_city']
      end

      if attributes.key?(:'postcard_from_name')
        self.postcard_from_name = attributes[:'postcard_from_name']
      end

      if attributes.key?(:'postcard_from_postal_code')
        self.postcard_from_postal_code = attributes[:'postcard_from_postal_code']
      end

      if attributes.key?(:'postcard_from_state')
        self.postcard_from_state = attributes[:'postcard_from_state']
      end

      if attributes.key?(:'reviews_io_configured')
        self.reviews_io_configured = attributes[:'reviews_io_configured']
      end

      if attributes.key?(:'sms_esp_twilio_uuid')
        self.sms_esp_twilio_uuid = attributes[:'sms_esp_twilio_uuid']
      end

      if attributes.key?(:'sms_phone_number')
        self.sms_phone_number = attributes[:'sms_phone_number']
      end

      if attributes.key?(:'transactional_esp_domain_user')
        self.transactional_esp_domain_user = attributes[:'transactional_esp_domain_user']
      end

      if attributes.key?(:'transactional_esp_domain_uuid')
        self.transactional_esp_domain_uuid = attributes[:'transactional_esp_domain_uuid']
      end

      if attributes.key?(:'transactional_esp_friendly_name')
        self.transactional_esp_friendly_name = attributes[:'transactional_esp_friendly_name']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          marketing_esp_domain_user == o.marketing_esp_domain_user &&
          marketing_esp_domain_uuid == o.marketing_esp_domain_uuid &&
          marketing_esp_friendly_name == o.marketing_esp_friendly_name &&
          postcard_from_address1 == o.postcard_from_address1 &&
          postcard_from_address2 == o.postcard_from_address2 &&
          postcard_from_city == o.postcard_from_city &&
          postcard_from_name == o.postcard_from_name &&
          postcard_from_postal_code == o.postcard_from_postal_code &&
          postcard_from_state == o.postcard_from_state &&
          reviews_io_configured == o.reviews_io_configured &&
          sms_esp_twilio_uuid == o.sms_esp_twilio_uuid &&
          sms_phone_number == o.sms_phone_number &&
          transactional_esp_domain_user == o.transactional_esp_domain_user &&
          transactional_esp_domain_uuid == o.transactional_esp_domain_uuid &&
          transactional_esp_friendly_name == o.transactional_esp_friendly_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [marketing_esp_domain_user, marketing_esp_domain_uuid, marketing_esp_friendly_name, postcard_from_address1, postcard_from_address2, postcard_from_city, postcard_from_name, postcard_from_postal_code, postcard_from_state, reviews_io_configured, sms_esp_twilio_uuid, sms_phone_number, transactional_esp_domain_user, transactional_esp_domain_uuid, transactional_esp_friendly_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = UltracartClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
