=begin
#UltraCart Rest API V2

#UltraCart REST API Version 2

OpenAPI spec version: 2.0.0
Contact: support@ultracart.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15-SNAPSHOT

=end

require 'date'

module UltracartClient
  class PaymentsConfigurationWireTransfer
    attr_accessor :accept_wire_transfer

    attr_accessor :restrictions

    attr_accessor :wire_transfer_accounting_code

    attr_accessor :wire_transfer_account_number

    attr_accessor :wire_transfer_bank_address

    attr_accessor :wire_transfer_deposit_to_account

    attr_accessor :wire_transfer_intermediate_routing_number

    attr_accessor :wire_transfer_routing_number

    attr_accessor :wire_transfer_surcharge_accounting_code

    attr_accessor :wire_transfer_surcharge_fee

    attr_accessor :wire_transfer_surcharge_perc

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'accept_wire_transfer' => :'acceptWireTransfer',
        :'restrictions' => :'restrictions',
        :'wire_transfer_accounting_code' => :'wireTransferAccountingCode',
        :'wire_transfer_account_number' => :'wireTransferAccountNumber',
        :'wire_transfer_bank_address' => :'wireTransferBankAddress',
        :'wire_transfer_deposit_to_account' => :'wireTransferDepositToAccount',
        :'wire_transfer_intermediate_routing_number' => :'wireTransferIntermediateRoutingNumber',
        :'wire_transfer_routing_number' => :'wireTransferRoutingNumber',
        :'wire_transfer_surcharge_accounting_code' => :'wireTransferSurchargeAccountingCode',
        :'wire_transfer_surcharge_fee' => :'wireTransferSurchargeFee',
        :'wire_transfer_surcharge_perc' => :'wireTransferSurchargePerc'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'accept_wire_transfer' => :'BOOLEAN',
        :'restrictions' => :'PaymentsConfigurationRestrictions',
        :'wire_transfer_accounting_code' => :'String',
        :'wire_transfer_account_number' => :'String',
        :'wire_transfer_bank_address' => :'String',
        :'wire_transfer_deposit_to_account' => :'String',
        :'wire_transfer_intermediate_routing_number' => :'String',
        :'wire_transfer_routing_number' => :'String',
        :'wire_transfer_surcharge_accounting_code' => :'String',
        :'wire_transfer_surcharge_fee' => :'String',
        :'wire_transfer_surcharge_perc' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'acceptWireTransfer')
        self.accept_wire_transfer = attributes[:'acceptWireTransfer']
      end

      if attributes.has_key?(:'restrictions')
        self.restrictions = attributes[:'restrictions']
      end

      if attributes.has_key?(:'wireTransferAccountingCode')
        self.wire_transfer_accounting_code = attributes[:'wireTransferAccountingCode']
      end

      if attributes.has_key?(:'wireTransferAccountNumber')
        self.wire_transfer_account_number = attributes[:'wireTransferAccountNumber']
      end

      if attributes.has_key?(:'wireTransferBankAddress')
        self.wire_transfer_bank_address = attributes[:'wireTransferBankAddress']
      end

      if attributes.has_key?(:'wireTransferDepositToAccount')
        self.wire_transfer_deposit_to_account = attributes[:'wireTransferDepositToAccount']
      end

      if attributes.has_key?(:'wireTransferIntermediateRoutingNumber')
        self.wire_transfer_intermediate_routing_number = attributes[:'wireTransferIntermediateRoutingNumber']
      end

      if attributes.has_key?(:'wireTransferRoutingNumber')
        self.wire_transfer_routing_number = attributes[:'wireTransferRoutingNumber']
      end

      if attributes.has_key?(:'wireTransferSurchargeAccountingCode')
        self.wire_transfer_surcharge_accounting_code = attributes[:'wireTransferSurchargeAccountingCode']
      end

      if attributes.has_key?(:'wireTransferSurchargeFee')
        self.wire_transfer_surcharge_fee = attributes[:'wireTransferSurchargeFee']
      end

      if attributes.has_key?(:'wireTransferSurchargePerc')
        self.wire_transfer_surcharge_perc = attributes[:'wireTransferSurchargePerc']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          accept_wire_transfer == o.accept_wire_transfer &&
          restrictions == o.restrictions &&
          wire_transfer_accounting_code == o.wire_transfer_accounting_code &&
          wire_transfer_account_number == o.wire_transfer_account_number &&
          wire_transfer_bank_address == o.wire_transfer_bank_address &&
          wire_transfer_deposit_to_account == o.wire_transfer_deposit_to_account &&
          wire_transfer_intermediate_routing_number == o.wire_transfer_intermediate_routing_number &&
          wire_transfer_routing_number == o.wire_transfer_routing_number &&
          wire_transfer_surcharge_accounting_code == o.wire_transfer_surcharge_accounting_code &&
          wire_transfer_surcharge_fee == o.wire_transfer_surcharge_fee &&
          wire_transfer_surcharge_perc == o.wire_transfer_surcharge_perc
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [accept_wire_transfer, restrictions, wire_transfer_accounting_code, wire_transfer_account_number, wire_transfer_bank_address, wire_transfer_deposit_to_account, wire_transfer_intermediate_routing_number, wire_transfer_routing_number, wire_transfer_surcharge_accounting_code, wire_transfer_surcharge_fee, wire_transfer_surcharge_perc].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = UltracartClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
